### ISSUE TITLE
Update CONTRIBUTION file PR and Issues link. Link has ben interchanged

### ISSUE THREAD

**Issue by kwekubright** [Scriptonauts/News360#41]

**Comment by niicode** [comment]
Hi @kwekubright can you please elaborate a bit on this issue its not clear.

**Comment by kwekubright** [comment]
Hi @niicode ,
There is a hyperlink for PR and Issues page in the contribution file. When the PR link is clicked  it leads to to the Issues page instead of the PR page.

Also when the Issues link is clicked it leads to the PR page instead of the Issues page

**Comment by niicode** [comment]
Hi @kwekubright  Noted the change I will implement that, Thanks🥂
